const std = @import("std");
const cli = @import("cli.zig");
const zon2lock = @import("zon2lock.zig");

fn writeInternal(arena: std.mem.Allocator, lock: zon2lock.Lock, out: *std.Io.Writer) !void {
    var env = try cli.fetchZigEnv(arena);
    defer env.deinit();
    const zig_version: std.SemanticVersion = try .parse(env.value.version);

    var pipe = try cli.pipe(arena, null, &.{ "nixfmt", "-v" });
    defer pipe.deinit();
    var buf: [1024]u8 = undefined;
    var pipe_writer = pipe.writer(&buf);
    const writer = &pipe_writer.interface;
    try writer.writeAll(
        \\# generated by zon2nix (https://github.com/Cloudef/zig2nix)
        \\
        \\{
        \\  linkFarm,
        \\  runCommand,
        \\  zig,
        \\  name ? "zig-packages",
        \\}:
        \\
        \\let
    );

    if (zig_version.minor >= 16) {
        try writer.writeAll(
            \\  fetchZig = { name, url, hash }: runCommand name {
            \\    src = url;
            \\    nativeBuildInputs = [ zig ];
            \\    outputHash = hash;
            \\    outputHashMode = "flat";
            \\  } ''
            \\    touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
            \\    hash="$(cd $TMPDIR && zig fetch --global-cache-dir "$TMPDIR" ${url})"
            \\    mv "$TMPDIR/p/$hash.tar.gz" "$out"
            \\  '';
            \\
        );
    } else {
        try writer.writeAll(
            \\  fetchZig = { name, url, hash }: runCommand name {
            \\    src = url;
            \\    nativeBuildInputs = [ zig ];
            \\    outputHash = hash;
            \\    outputHashMode = "nar";
            \\  } ''
            \\    hash="$(zig fetch --global-cache-dir "$TMPDIR" ${url})"
            \\    mv "$TMPDIR/p/$hash" "$out"
            \\    chmod 755 "$out"
            \\  '';
            \\
        );
    }

    try writer.writeAll(
        \\in linkFarm name [
        \\
    );

    var iter = lock.map.iterator();
    while (iter.next()) |kv| {
        const zhash = kv.key_ptr.*;
        const dep = kv.value_ptr;
        try writer.writeAll("{\n");
        if (zig_version.minor >= 16) {
            try writer.print("name = \"{s}.tar.gz\";\n", .{zhash});
        } else {
            try writer.print("name = \"{s}\";\n", .{zhash});
        }
        try writer.writeAll("path = fetchZig {\n");
        try writer.print("name = \"{s}\";\n", .{dep.name});
        try writer.print("url = \"{s}\";\n", .{dep.url});
        try writer.print("hash = \"{s}\";\n", .{dep.hash});
        try writer.writeAll("};\n");
        try writer.writeAll("}\n");
    }

    try writer.writeAll("]");
    try writer.flush();
    pipe.close();
    var pipe_reader = pipe.reader(&buf);
    _ = pipe_reader.interface.streamDelimiter(out, 0) catch |err| switch (err) {
        error.EndOfStream => {},
        else => |e| return e,
    };

    return switch (try pipe.finish()) {
        .Exited => |status| switch (status) {
            0 => {},
            else => error.NixFmtFailed,
        },
        else => error.NixFmtFailed,
    };
}

pub fn write(allocator: std.mem.Allocator, cwd: std.fs.Dir, path: []const u8, writer: *std.Io.Writer) !void {
    var arena_state: std.heap.ArenaAllocator = .init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var lock = (try zon2lock.parsePath(arena, cwd, path)) orelse return;
    defer lock.deinit();
    try writeInternal(arena, lock, writer);
}
