name: automation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@master
        with:
          name: zig2nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nix run .#update-versions > versions.json
          nix run .#update-templates
          nix run .#test.all
          nix run .#readme > README.md
      - uses: test-room-7/action-update-file@v2.0.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}
          file-path: |
            versions.json
            templates/**
            README.md
          commit-msg: Automatic update
          github-token: ${{ secrets.GITHUB_TOKEN }}
