name: pr

on:
  pull_request:
  workflow_dispatch:

jobs:
  pr:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix run .#update-templates
          nix run .#test.all
          nix run .#readme
